<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>wollet-client</AssemblyName>
    <Product>Wollet Client</Product>
    <Description>Wollet Windows Client</Description>
    <InformationalVersion Condition="'$(Version)' == ''">unknown</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Net.Http" />
    <ProjectReference Include="../Wollet.Client.Application/Wollet.Client.Application.csproj" />
    <InternalsVisibleTo Include="Wollet.Client.Windows.Tests" />
    <ProjectReference Include="../Wollet.Client.Core/Wollet.Client.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
  </ItemGroup>
</Project>
